export const bdLocations = {
  Dhaka: [
    "Dhaka Sadar",
    "Dhanmondi",
    "Gulshan",
    "Banani",
    "Uttara",
    "Mirpur",
    "Mohammadpur",
    "Jatrabari",
    "Badda",
    "Tejgaon",
    "Motijheel",
    "Savar",
    "Keraniganj",
    "Nawabganj",
    "Dhamrai",
    "Dohar",
    "Gazipur Sadar",
    "Kaliakair",
    "Tongi",
    "Kapasia",
    "Manikganj Sadar",
    "Saturia",
    "Ghior",
    "Shibalaya",
    "Singair",
    "Harirampur",
    "Munshiganj Sadar",
    "Gazaria",
    "Sirajdikhan",
    "Narayanganj Sadar",
    "Rupganj",
    "Bandar",
    "Narsingdi Sadar",
    "Belabo",
    "Palash",
    "Kishoreganj Sadar",
    "Karimganj",
    "Katiadi",
    "Hossainpur",
    "Itna",
    "Bajitpur",
    "Tangail Sadar",
    "Delduar",
    "Basail",
    "Gopalpur",
    "Bhuapur",
    "Nagarpur",
    "Mirzapur",
    "Sakhipur",
    "Kalihati",
    "Madhupur",
    "Ghatail",
    "Dhanbari",
    "Faridpur Sadar",
    "Boalmari",
    "Alfadanga",
    "Madhukhali",
    "Nagarkanda",
    "Bhanga",
    "Gopalganj Sadar",
    "Kashiani",
    "Muksudpur",
    "Tungipara",
    "Madaripur Sadar",
    "Rajoir",
    "Shibchar",
    "Rajbari Sadar",
    "Baliakandi",
    "Pangsha",
    "Shariatpur Sadar",
    "Bhedarganj",
    "Naria",
    "Zanjira"
  ],
  Chattogram: [
    "Chattogram Sadar",

    "Kotwali",
    "Pahartali",
    "Panchlaish",
    "Hathazari",
    "Rangunia",
    "Boalkhali",
    "Anwara",
    "Banshkhali",
    "Chandanaish",
    "Fatikchhari",
    "Lohagara",
    "Mirsharai",
    "Patiya",
    "Rangunia",
    "Raozan",
    "Sandwip",
    "Satkania",
    "Sitakunda",
    "Karnaphuli",
  ],
  Khulna: [
    "Khulna Sadar",
    "Sonadanga",
    "Khalishpur",
    "Daulatpur",
    "Rupsha",
    "Batiaghata",
    "Dumuria",
    "Dacope",
    "Phultala",
    "Terokhada",
    "Paikgachha",
    "Bagerhat Sadar",
    "Mongla",
    "Fultala",
    "Khalishpur",
    "Dighalia",
  ],
  Rajshahi: [
    "Rajshahi Sadar",
    "Boalia",
    "Paba",
    "Motihar",
    "Rajpara",
    "Bagmara",
    "Tanore",
    "Durgapur",
    "Puthia",
    "Charghat",
    "Godagari",
    "Mohonpur",
  ],
  Sylhet: [
    "Sylhet Sadar",
    "South Surma",
    "Jakiganj",
    "Companiganj",
    "Bianibazar",
    "Beanibazar",
    "Balaganj",
    "Golapganj",
    "Gowainghat",
    "Jaintiapur",
    "Fenchuganj",
    "Kamalganj",
    "Kanaighat",
    "Osmani Nagar",
    "Zakiganj",
  ],
  Barisal: [
    "Barisal Sadar",
    "Bakerganj",
    "Babuganj",
    "Muladi",
    "Agailjhara",
    "Banaripara",
    "Gournadi",
    "Hizla",
    "Mehendiganj",
    "Uzirpur",
  ],
  Rangpur: [
    "Rangpur Sadar",
    "Gangachara",
    "Taraganj",
    "Kaunia",
    "Badarganj",
    "Mithapukur",
    "Pirganj",
    "Pirganj (Thakurgaon)",
    "Pirgachha",
    "Thakurgaon Sadar",
    "Dimla",
    "Domar",
    "Kurigram Sadar",
    "Nageshwari",
    "Ranisankail",
  ],
  Mymensingh: [
    "Mymensingh Sadar",
    "Bhaluka",
    "Gafargaon",
    "Muktagacha",
    "Trishal",
    "Ishwarganj",
    "Nandail",
    "Phulpur",
    "Haluaghat",
    "Fulbaria",
    "Gouripur",
    "Jamalpur Sadar",
    "Sherpur Sadar",
  ],
};
   